# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ClassifyDesired
                                 A QGIS plugin
 Classify the desired area.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-14
        copyright            : (C) 2021 by Sivabhorn Kongjan
        email                : sivabhornk60@nu.ac.th
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ClassifyDesired class from file ClassifyDesired.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .classify_desired import ClassifyDesired
    return ClassifyDesired(iface)
